# Generated by Django 5.0.4 on 2024-04-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
