# Generated by Django 5.0.4 on 2024-04-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracking', '0002_rename_finance_tracking_coachfinances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachfinances',
            name='last_payment_balance',
            field=models.IntegerField(default=0),
        ),
    ]
