# Generated by Django 5.0.2 on 2024-04-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_platform', '0003_annoucements'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Annoucements',
        ),
    ]
