# Generated by Django 5.0.2 on 2024-03-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('membership_approved', models.BooleanField(default=False)),
                ('attendance_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'member_logs',
            },
        ),
    ]
