# Generated by Django 5.0.2 on 2024-04-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_logs', '0002_remove_member_password_remove_member_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
    ]
