'use client';
export { default as Navbar } from './general/nav/navbar';
export { default as Footer } from './general/footer';
export { default as DarkMode } from './general/buttons/darkModeButton';
export { default as UnAuthorized } from './general/authorization/unAuthorized';
export { default as Deactivated } from './general/authorization/deactivated';
export { default as CustomDropdown } from './general/buttons/dropdownMenu';
export { default as CustomButton } from './general/buttons/manageButton';
export { default as Menu } from './interface/menu';
export { default as Body } from './general/body';