# Generated by Django 5.0.3 on 2024-04-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes_offered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=200)),
                ('instructor_name', models.CharField(max_length=100)),
                ('class_datetime', models.DateTimeField()),
                ('participants', models.JSONField()),
            ],
            options={
                'db_table': 'classes_offered_db',
            },
        ),
    ]
