# Generated by Django 5.0.3 on 2024-04-02 23:58
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_offered', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes_offered',
            name='participants',
        ),

        migrations.AddField(
            model_name='classes_offered',
            name='participants', 
            field = django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
    ]
