# Generated by Django 5.0.3 on 2024-04-03 00:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_offered', '0004_classes_offered_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_offered',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None),
        ),
    ]
