# Generated by Django 5.0.4 on 2024-04-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_offered', '0006_alter_classes_offered_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_offered',
            name='class_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
